'use server';
/**
 * @fileOverview This file implements a Genkit flow for generating realistic phishing email template content
 * based on a chosen scenario, for educational and ethical training purposes.
 *
 * - generatePhishingEmailTemplate - A function that triggers the AI to generate the email template.
 * - GeneratePhishingEmailTemplateInput - The input type for the generatePhishingEmailTemplate function.
 * - GeneratePhishingEmailTemplateOutput - The return type for the generatePhishingEmailTemplate function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const GeneratePhishingEmailTemplateInputSchema = z.object({
  scenario: z.string().describe('The phishing scenario to generate an email template for (e.g., "password reset scam", "fake invoice").'),
});
export type GeneratePhishingEmailTemplateInput = z.infer<typeof GeneratePhishingEmailTemplateInputSchema>;

const GeneratePhishingEmailTemplateOutputSchema = z.object({
  subject: z.string().describe('The generated subject line for the phishing email.'),
  body_html: z.string().describe('The HTML content of the phishing email body. It MUST include a placeholder for a tracking pixel (e.g., <img src="{{TRACKING_PIXEL_URL}}" width="1" height="1">) and a phishing link (e.g., <a href="{{PHISHING_LINK_URL}}">Click Here</a>).'),
  disclaimer: z.string().describe('A clear, ethical disclaimer message to be added to the email, stating that this is a simulated training exercise and not a real phishing attempt.'),
});
export type GeneratePhishingEmailTemplateOutput = z.infer<typeof GeneratePhishingEmailTemplateOutputSchema>;

export async function generatePhishingEmailTemplate(input: GeneratePhishingEmailTemplateInput): Promise<GeneratePhishingEmailTemplateOutput> {
  return generatePhishingEmailTemplateFlow(input);
}

const generatePhishingEmailPrompt = ai.definePrompt({
  name: 'generatePhishingEmailPrompt',
  input: { schema: GeneratePhishingEmailTemplateInputSchema },
  output: { schema: GeneratePhishingEmailTemplateOutputSchema },
  prompt: `You are an expert in cybersecurity training and social engineering, tasked with creating highly realistic yet ethically responsible phishing email templates for educational simulations.

Your goal is to generate a convincing phishing email template based on the provided scenario. The email must look legitimate to a casual observer but should be clearly identifiable as a simulation after a debrief.

Important Ethical Guidelines:
1. This email is for educational purposes ONLY, to train users to identify phishing attempts.
2. It must include a prominent disclaimer generated by you, stating it is a simulation.
3. DO NOT generate content that could be used for actual malicious activities.
4. Focus on common phishing tactics like urgency, fear, authority impersonation, or attractive offers.

Scenario: {{{scenario}}}

Generate the following:
1.  **subject**: A compelling and realistic subject line that aligns with the scenario.
2.  **body_html**: The full HTML content of the email body.
    -   It MUST contain a placeholder for a tracking pixel: <img src="{{TRACKING_PIXEL_URL}}" width="1" height="1">
    -   It MUST contain at least one clear phishing link placeholder: <a href="{{PHISHING_LINK_URL}}">Click Here</a> or similar anchor text.
    -   Ensure the HTML is well-formed and visually convincing.
3.  **disclaimer**: A short, clear, and unambiguous message to be appended to the email body (or displayed prominently), stating that this is a simulated phishing exercise for training purposes only, and no real sensitive information should be entered.

The generated content will be reviewed by an administrator for ethical use before being deployed in a training campaign.`,
});

const generatePhishingEmailTemplateFlow = ai.defineFlow(
  {
    name: 'generatePhishingEmailTemplateFlow',
    inputSchema: GeneratePhishingEmailTemplateInputSchema,
    outputSchema: GeneratePhishingEmailTemplateOutputSchema,
  },
  async (input) => {
    const { output } = await generatePhishingEmailPrompt(input);
    if (!output) {
      throw new Error('Failed to generate phishing email template content.');
    }
    return output;
  }
);
